server:
  port: 8888
  context-path: /cmfz

  #  热部署
  jsp-servlet:
    init-parameters:
      development: true



spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cmfz
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  #    视图解析器
  mvc:
    view:
      prefix: /
      suffix: .jsp


  #   文件上传
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
    #    编码
    encoding:
      charset: utf-8
      force: true


#mybatis:
#  type-aliases-package: com.baizhi.entity
#  mapper-locations: com/baizhi/dao/*Dao.xml

##分页
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: com/baizhi/dao/*Dao.xml
